### ISSUE TITLE
Supporting ES5 style commonjs require

### ISSUE THREAD

**Issue by MrOrz** [tomchentw/goflux#10]
Currently only ES6 style import / export is supported. When users use commonjs-style `require`, they will have to use `Goflux['default']` to access goflux class, which is a bit awkward.

https://github.com/tomchentw/goflux/blob/master/lib/index.js#L11

**Comment by tomchentw** [comment]
Might change it to `const {Goflux} = require("goflux");` instead

**Comment by tomchentw** [comment]
Closed by #16
